#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model RespirationModeling.Tests.TestAlvVent
 Dymola Version 2023x, 2022-10-07 translated this at Fri Mar 21 19:33:09 2025

  Evaluate = true;
 */

#include <matrixop.h>
#include "matrixop.c"
#if defined(DynSimStruct)
static double DymArrays0[3]={0.022392199999999998, 0.0222629, 101325.0};
static double DymArrays1[4]={140.0, 140.0, 40.0, 0.0};
#endif
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    0
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    48
#define NWP_   34
#define NP_    0
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1900187496
#define NHash2_ 1151577180
#define NHash3_ -542271829
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  2
#define NSamp_ 0
#define NCons_ 0
#define NA_    3
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="RespirationModeling.Tests.TestAlvVent";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/kofra/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations
InitialSection

InitialSection
#if defined(DynSimStruct)
memcpy(&DYNX(W_,5), &DymArrays0, sizeof(double)*3);
DYNX(W_,14) = 8.1E-05;
DYNX(W_,16) = 101325.0144354;
DYNX(W_,18) = 310.15;
DYNX(W_,20) = 0.2095;
DYNX(W_,22) = 0.0004;
DYNX(W_,24) = 0.00016666666666667;
DYNX(W_,26) = 0.00018666666666667;
memcpy(&DYNX(W_,28), &DymArrays1, sizeof(double)*4);
DYNX(W_,33) = 0.01;
DYNX(W_,9) = 37.0;
DYNX(W_,2) = 6279.884727650507;
DYNX(W_,8) = 1.210479183622438;
DYNX(W_,3) = 4.179877333333408E-06;
DYNX(W_,4) = 3.7104833333334073E-06;
DYNX(W_,23) = 0.0004;
DYNX(W_,21) = 0.2095;
DYNX(W_,25) = 0.00016666666666667;
DYNX(W_,27) = 0.00018666666666667;
DYNX(W_,15) = 8.1E-05;
DYNX(W_,11) = 0.00016666666666667;
DYNX(W_,13) = 0.0004;
DYNX(W_,12) = 0.2095;
DYNX(W_,10) = 0.00018666666666667;
DYNX(W_,0) = 101325.0144354;
DYNX(W_,1) = 310.15;
DYNX(W_,17) = 101325.0144354;
DYNX(W_,32) = 8.1E-05;
DYNX(W_,19) = 310.15;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection

AcceptedSection1

AcceptedSection2
DYNX(W_,46) = 40+(IF LessTime(0, 0) THEN 0 ELSE IF LessTime(140, 1) THEN DYNTime
   ELSE 140);
DYNX(W_,47) = 0.01*DYNX(W_,46);
DYNX(W_,34) = 8.1E-05*DYNX(W_,47);
DYNX(W_,38) = 0.8261191216914897*DYNX(W_,34);
DYNX(W_,39) = 0.2095*DYNX(W_,38);
DYNX(W_,42) = DYNX(W_,39)-4.179877333333408E-06;
DYNX(W_,41) = DYNX(W_,38)-4.6939400000000037E-07;
DYNX(W_,45) = divGuarded(DYNX(W_,42),"alvVent.VO2e_STPD",DYNX(W_,41),
  "alvVent.VAe_STPD");
DYNX(W_,35) = 95045.12970774948*DYNX(W_,45);
DYNX(W_,40) = 0.0004*DYNX(W_,38);
DYNX(W_,43) = 3.7104833333334073E-06+DYNX(W_,40);
DYNX(W_,44) = divGuarded(DYNX(W_,43),"alvVent.VCO2e_STPD",DYNX(W_,41),
  "alvVent.VAe_STPD");
DYNX(W_,36) = 95045.12970774948*DYNX(W_,44);
DYNX(W_,37) = 1.210479183622438*DYNX(W_,41);

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("alvVent.VAi_BTPS", "[m3/s|ml/min]", 34, 0.0, 0.0,0.0,\
1.6666666666666667E-08,0,512)
DeclareVariable("alvVent.pressure", "[Pa|mmHg]", 0, 101325.0144354, 0.0,0.0,\
133.322387415,0,513)
DeclareVariable("alvVent.temperature", "[K|degC]", 1, 310.15, 0.0,1E+100,1.0,0,513)
DeclareVariable("alvVent.pAO2", "[Pa|mmHg]", 35, 0.0, 0.0,0.0,133.322387415,0,512)
DeclareVariable("alvVent.pACO2", "[Pa|mmHg]", 36, 0.0, 0.0,0.0,133.322387415,0,512)
DeclareVariable("alvVent.VAe_BTPS", "[m3/s|ml/min]", 37, 0.0, 0.0,0.0,\
1.6666666666666667E-08,0,512)
DeclareVariable("alvVent.pH2O", "[Pa|mmHg]", 2, 6279.884727650507, 0.0,0.0,\
133.322387415,0,513)
DeclareVariable("alvVent.VO2_STPD", "[m3/s|ml/min]", 3, 4.179877333333408E-06, \
0.0,0.0,1.6666666666666667E-08,0,513)
DeclareVariable("alvVent.VCO2_STPD", "[m3/s|ml/min]", 4, 3.7104833333334073E-06,\
 0.0,0.0,1.6666666666666667E-08,0,513)
DeclareVariable("alvVent.VAi_STPD", "[m3/s|ml/min]", 38, 0.0, 0.0,0.0,\
1.6666666666666667E-08,0,512)
DeclareVariable("alvVent.VO2i_STPD", "[m3/s|ml/min]", 39, 0.0, 0.0,0.0,\
1.6666666666666667E-08,0,512)
DeclareVariable("alvVent.VCO2i_STPD", "[m3/s|ml/min]", 40, 0.0, 0.0,0.0,\
1.6666666666666667E-08,0,512)
DeclareVariable("alvVent.VAe_STPD", "[m3/s|ml/min]", 41, 0.0, 0.0,0.0,\
1.6666666666666667E-08,0,512)
DeclareVariable("alvVent.VO2e_STPD", "[m3/s|ml/min]", 42, 0.0, 0.0,0.0,\
1.6666666666666667E-08,0,512)
DeclareVariable("alvVent.VCO2e_STPD", "[m3/s|ml/min]", 43, 0.0, 0.0,0.0,\
1.6666666666666667E-08,0,512)
DeclareVariable("alvVent.FACO2dry", "[1|%]", 44, 0.0, 0.0,0.0,0.01,0,512)
DeclareVariable("alvVent.FAO2dry", "[1|%]", 45, 0.0, 0.0,0.0,0.01,0,512)
DeclareVariable("alvVent.VmO2stand", "O2 molar volume at 0\302\260C 760 mmHg [m3/mol]",\
 5, 0.022392199999999998, 0.0,1E+100,0.0,0,513)
DeclareVariable("alvVent.VmCO2stand", "CO2 molar volume at 0\302\260C 760 mmHg [m3/mol]",\
 6, 0.0222629, 0.0,1E+100,0.0,0,513)
DeclareVariable("alvVent.Pstand", "[Pa|bar]", 7, 101325, 0.0,0.0,0.0,0,513)
DeclareVariable("alvVent.STPD_to_BTPS", "[1]", 8, 1.210479183622438, 0.0,0.0,0.0,\
0,513)
DeclareVariable("alvVent.tempC", "[K]", 9, 37.0, 0.0,0.0,0.0,0,513)
DeclareVariable("alvVent.O2M", "[mol/s|mmol/min]", 10, 0.00018666666666667, \
0.0,0.0,0.0,0,513)
DeclareVariable("alvVent.CO2M", "[mol/s|mmol/min]", 11, 0.00016666666666667, \
0.0,0.0,0.0,0,513)
DeclareVariable("alvVent.FiO2d", "[1|%]", 12, 0.2095, 0.0,0.0,0.01,0,513)
DeclareVariable("alvVent.FiCO2d", "[1|%]", 13, 0.0004, 0.0,0.0,0.01,0,513)
DeclareVariable("VAi.k", "Constant VolumeFlowRate output value [m3/s|ml/min]", 14,\
 8.1E-05, 0.0,0.0,1.6666666666666667E-08,0,513)
DeclareVariable("VAi.y", "VolumeFlowRate constant [m3/s|ml/min]", 15, 8.1E-05, \
0.0,0.0,1.6666666666666667E-08,0,513)
DeclareVariable("pressure.k", "Constant Pressure output value [Pa|mmHg]", 16, \
101325.0144354, 0.0,0.0,133.322387415,0,513)
DeclareVariable("pressure.y", "Pressure constant [Pa|mmHg]", 17, 101325.0144354,\
 0.0,0.0,133.322387415,0,513)
DeclareVariable("temperature.k", "Constant Temperature output value [K|degC]", 18,\
 310.15, 0.0,1E+100,1.0,0,513)
DeclareVariable("temperature.y", "Temperature constant [K|degC]", 19, 310.15, \
0.0,1E+100,1.0,0,513)
DeclareVariable("FiO2d.k", "Constant Fraction output value [1|%]", 20, 0.2095, \
0.0,0.0,0.01,0,513)
DeclareVariable("FiO2d.y", "Fraction constant [1|%]", 21, 0.2095, 0.0,0.0,0.01,0,513)
DeclareVariable("FiCO2d.k", "Constant Fraction output value [1|%]", 22, 0.0004, \
0.0,0.0,0.01,0,513)
DeclareVariable("FiCO2d.y", "Fraction constant [1|%]", 23, 0.0004, 0.0,0.0,0.01,\
0,513)
DeclareVariable("MCO2.k", "Constant MolarFlowRate output value [mol/s|mmol/min]",\
 24, 0.00016666666666667, 0.0,0.0,0.0,0,513)
DeclareVariable("MCO2.y", "MolarFlowRate constant [mol/s|mmol/min]", 25, \
0.00016666666666667, 0.0,0.0,0.0,0,513)
DeclareVariable("MO2.k", "Constant MolarFlowRate output value [mol/s|mmol/min]",\
 26, 0.00018666666666667, 0.0,0.0,0.0,0,513)
DeclareVariable("MO2.y", "MolarFlowRate constant [mol/s|mmol/min]", 27, \
0.00018666666666667, 0.0,0.0,0.0,0,513)
DeclareVariable("ramp.height", "Height of ramps", 28, 140, 0.0,0.0,0.0,0,513)
DeclareVariable("ramp.duration", "Duration of ramp (= 0.0 gives a Step) [s]", 29,\
 140, 0.0,1E+100,0.0,0,513)
DeclareVariable("ramp.y", "Connector of Real output signal", 46, 0.0, 0.0,0.0,\
0.0,0,512)
DeclareVariable("ramp.offset", "Offset of output signal y", 30, 40, 0.0,0.0,0.0,\
0,513)
DeclareVariable("ramp.startTime", "Output y = offset for time < startTime [s]", 31,\
 0, 0.0,0.0,0.0,0,513)
DeclareVariable("product1.u1", "Connector of Real input signal 1 [1]", 47, 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("product1.u2", "Connector of Real input signal 2 [m3/s]", 32, \
8.1E-05, 0.0,0.0,0.0,0,513)
DeclareAlias2("product1.y", "Connector of Real output signal [m3/s]", \
"alvVent.VAi_BTPS", 1, 5, 34, 0)
DeclareVariable("gain.k", "Gain value multiplied with input signal [1|%]", 33, \
0.01, 0.0,0.0,0.0,0,513)
DeclareAlias2("gain.u", "Input signal connector", "ramp.y", 1, 5, 46, 0)
DeclareAlias2("gain.y", "Output signal connector [1]", "product1.u1", 1, 5, 47, 0)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
EndDataBlock
